# Locally override default configurations
#
# This file overrides configurations set in `config/config.defaults.yml`.
# Keep in mind that environment variables override setting in this file.
#
# Usage:
#
# Copy this file from `config/config.example.yml` to `config/config.yml`
#

development:
  # domain: <%= ENV['DOMAIN'] %>

  secret_key_base: "af3e03847621a11be1667fe5a114ffb9a200418782dff5e28b5ac11bf9d97b648c6b6744725b13e3da8fcf632226bd89aeec122caa72ab1dc3bcef05b4a7b97a"

  # Default bucket
  s3_bucket_name: cine-equipment-images

  # AWS S3 region
  s3_region: eu-west-1

  # Cache-Control: max-age time in seconds for assets uploaded to S3.
  # Default is one day. Normally, you can use the default. Links to images have
  # modification timestamp appended as query parameter and that should be enough for cache invalidation.
  s3_cache_max_age: 86400

  # Bucket for files users upload directly to S3. You can add an expiration policy to these files.
  s3_upload_bucket_name: cine-equipment-images-tmp

  # AWS keys
  # aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  # aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

  google_maps_key: AIzaSyDmIHAmuDWg2pc_WlE7sfoEnV0uVXVQvfQ

test:
  # Add local `test` environment configuration overrides here

staging:
  # Add local `staging` environment configuration overrides here

production:
  domain: "staging.cine.equipment"

  secret_key_base: "af3e03847621a11be1667fe5a114ffb9a200418782dff5e28b5ac11bf9d97b648c6b6744725b13e3da8fcf632226bd89aeec122caa72ab1dc3bcef05b4a7b97a"

  # Default bucket
  s3_bucket_name: cine-equipment-images

  # AWS S3 region
  s3_region: eu-west-1

  # Cache-Control: max-age time in seconds for assets uploaded to S3.
  # Default is one day. Normally, you can use the default. Links to images have
  # modification timestamp appended as query parameter and that should be enough for cache invalidation.
  s3_cache_max_age: 86400

  # Bucket for files users upload directly to S3. You can add an expiration policy to these files.
  s3_upload_bucket_name: cine-equipment-images-tmp

  # AWS keys
  # aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  # aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_access_key_id: AKIAIW4NVYCKKREWPEUQ
  aws_secret_access_key: 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

  google_maps_key: AIzaSyDmIHAmuDWg2pc_WlE7sfoEnV0uVXVQvfQ
